name: Docker Image CI

on:
  push:
    branches:
      - staging
      - trying

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - name: Pull submodules
        run: git submodule update --init --recursive

      - name: Build OpenedX
        run: docker build . --target base --file ./Dockerfile --tag eoluchile/dgd-edx:${GITHUB_SHA} --tag eoluchile/dgd-edx:latest

      - name: Build OpenedX static files
        run: docker build . --target s3 --file ./Dockerfile --tag eoluchile/dgd-edx:static-${GITHUB_SHA} --tag eoluchile/dgd-edx:static-latest

      - name: Push
        run: |
          echo "${DOCKERHUB_PASSWORD}" | docker login --username ${DOCKERHUB_USER} --password-stdin
          docker push eoluchile/dgd-edx:${GITHUB_SHA}
          docker push eoluchile/dgd-edx:latest
          docker push eoluchile/dgd-edx:static-${GITHUB_SHA}
          docker push eoluchile/dgd-edx:static-latest
        env:
          DOCKERHUB_USER: ${{ secrets.DOCKERHUB_USER }}
          DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
